CREATE TABLE TBL_SHOPPING_ITEM (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	BRAND VARCHAR(255) NOT NULL,
	TYPE VARCHAR(20) NOT NULL,
	IMAGE VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TBL_SUPPLIER(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	LATITUDE DECIMAL(5,2) NOT NULL,
	LONGITUDE DECIMAL(5,2) NOT NULL,
	PRIMARY KEY(ID)
);